"""remove role column from user and admins

Revision ID: 0d8d60bf1deb
Revises: c75f7772b3ba
Create Date: 2025-08-05 02:48:13.837172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d8d60bf1deb'
down_revision = 'c75f7772b3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
