"""add is_verified column to admin

Revision ID: 429d2e0eff48
Revises: e5ddcf64d89f
Create Date: 2025-08-12 21:33:10.698879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429d2e0eff48'
down_revision = 'e5ddcf64d89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
