"""add chatbot_logs table

Revision ID: 515c774ec8b5
Revises: 6e4a7192cd23
Create Date: 2025-10-06 13:21:59.633683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515c774ec8b5'
down_revision = '6e4a7192cd23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot_logs')
    # ### end Alembic commands ###
