"""tambah customer user id

Revision ID: 6964c75447da
Revises: d9a70819bec1
Create Date: 2025-11-03 10:37:37.092804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6964c75447da'
down_revision = 'd9a70819bec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nomer', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
