"""create broadcast table

Revision ID: 6e0683a6ca41
Revises: f53fb149a701
Create Date: 2025-11-01 12:56:28.730563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0683a6ca41'
down_revision = 'f53fb149a701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomor', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broadcast')
    # ### end Alembic commands ###
