"""Change pricing.price to string

Revision ID: 9db451fe4b65
Revises: b8d74be8025d
Create Date: 2025-10-22 17:15:52.048783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9db451fe4b65'
down_revision = 'b8d74be8025d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
