"""update chatbot_logs with only id, name, file_url

Revision ID: b8d74be8025d
Revises: 515c774ec8b5
Create Date: 2025-10-06 13:34:40.040257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8d74be8025d'
down_revision = '515c774ec8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.alter_column('file_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_constraint('chatbot_logs_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('message')
        batch_op.drop_column('session_id')
        batch_op.drop_column('response')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('session_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('message', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('chatbot_logs_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.alter_column('file_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
