"""updatenewmigrationsnew

Revision ID: f53fb149a701
Revises: 577fd137ffd0
Create Date: 2025-10-22 19:00:13.194858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f53fb149a701'
down_revision = '577fd137ffd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(display_width=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(display_width=20),
               nullable=True)

    # ### end Alembic commands ###
